### ISSUE TITLE
PGSQL -v 13 versus 9.6: Cherokee + PGSQL Installer

### ISSUE THREAD

**Issue by waidyanatha** [sahana/eden_deploy_manual#11]
Debian 10 already comes with pgsql -v 13 (is what I read).... so I purged it to install 9.6 otherwise, when I change 000_config.py and run "clean" it was grumbling
The cherokee+pgsql script is looking for /etc/postgresql/9.6 and cannot find since /etc/postgresql/13 is already there and maybe isn't allowing to install 9.6 to install

After purging I ran the manual install again but it didn't install because of this error
"Package ptop is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  pgtop"

Then I manually install pgsql-9.6 after omitting the "ptop" package from [command line here](https://github.com/sahana/eden_deploy_manual/blob/1b3fdf83482fb0aa479a022859054277e3a50dcd/install-eden-cherokee-postgis.sh#L622) 

Perhaps gptop needs removing

What about migrating to PGSQ -V 13?

**Comment by flavour** [comment]
I copied the Postgres version choice from the nginx script to the cherokee one.
This uses postgresql-11 for Buster & also handles the ptop package not being included
