### ISSUE TITLE
Postgis changes to cherokee-psql-config

### ISSUE THREAD

**Issue by waidyanatha** [sahana/eden_deploy_manual#13]
In the config file [configure-eden-cherokee-postgis.sh](https://github.com/sahana/eden_deploy_manual/blob/master/configure-eden-cherokee-postgis.sh)
Now that both `postgresql-11` and `postgresql-9.6` are used you'll need to change [this piece of code](https://github.com/sahana/eden_deploy_manual/blob/f8ac0acf97e497bb39f93befe0e2370961f0f817/configure-eden-cherokee-postgis.sh#L74) to possibly include a `if` and `fi` to resolve the two versions. 

Although I installed `postgresql-11-postgis-2.5` what I have is `/usr/share/postgresql/11/extension/postgis--3.1.3.sql`
I can't remember if it is because I might have installed `postgresql-11-postgis-3` before.

**Comment by flavour** [comment]
That line is commented...it's the old way of doing things the new way is the line below it:
CREATE EXTENSION postgis;

The new line doesn't need changing for each version :)
